import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

// Read source files
const shell = readFileSync(resolve(root, "src/teleprompter.html"), "utf8");
const css = readFileSync(resolve(root, "src/teleprompter.css"), "utf8");
const appJs = readFileSync(resolve(root, "src/app.js"), "utf8");
const parserJs = readFileSync(resolve(root, "src/parser.js"), "utf8");
const purify = readFileSync(
	resolve(root, "node_modules/dompurify/dist/purify.min.js"),
	"utf8",
);
const guideShell = readFileSync(resolve(root, "src/guide.html"), "utf8");
const guideCss = readFileSync(resolve(root, "src/guide.css"), "utf8");

// Strip `export` keywords so parser.js is valid inside the IIFE
const parserBrowser = parserJs.replace(/^export\s+/gm, "").trimEnd();

// Assemble teleprompter
const inlined = shell
	.replace("<!-- INJECT:CSS -->", css)
	.replace("<!-- INJECT:DOMPURIFY -->", `<script>${purify}</script>`)
	.replace("<!-- INJECT:APP -->", `${parserBrowser}\n\n${appJs}`);

// Assemble guide
const guideHtml = guideShell.replace("<!-- INJECT:CSS -->", guideCss);

// Write dist
mkdirSync(resolve(root, "dist"), { recursive: true });
writeFileSync(resolve(root, "dist/teleprompter.html"), inlined, "utf8");
console.log(
	`Built: dist/teleprompter.html (${Buffer.byteLength(inlined, "utf8")} bytes)`,
);

// Compute SHA-256 hashes of all inline <script> blocks so the Worker can emit
// a strict Content-Security-Policy without 'unsafe-inline'.
const SCRIPT_BLOCK_RE = /<script>([\s\S]*?)<\/script>/g;
const cspHashes = [];
for (const match of inlined.matchAll(SCRIPT_BLOCK_RE)) {
	const hash = createHash("sha256").update(match[1]).digest("base64");
	cspHashes.push(`'sha256-${hash}'`);
}
const cspScriptHashes = cspHashes.join(" ");

// Generate worker/src/template.ts so the Worker can import the HTML and demo
// script as TypeScript modules (avoids HTML/MD module resolution issues in
// Miniflare/vitest).
const demoScript = readFileSync(
	resolve(root, "scripts/jfk-inaugural.md"),
	"utf8",
);
const templateTs =
	`// THIS FILE IS GENERATED BY scripts/build.js — DO NOT EDIT MANUALLY.\n` +
	`// Run \`npm run build\` to regenerate from src/ source files.\n` +
	`export const HTML = ${JSON.stringify(inlined)};\n` +
	`export const DEMO_SCRIPT = ${JSON.stringify(demoScript)};\n` +
	`export const GUIDE_HTML = ${JSON.stringify(guideHtml)};\n` +
	`export const CSP_SCRIPT_HASHES = ${JSON.stringify(cspScriptHashes)};\n`;
writeFileSync(resolve(root, "worker/src/template.ts"), templateTs, "utf8");
console.log("Generated: worker/src/template.ts");
