import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const html = readFileSync(resolve(root, "teleprompter.html"), "utf8");
const purify = readFileSync(
	resolve(root, "node_modules/dompurify/dist/purify.min.js"),
	"utf8",
);

// Remove the development DOMPurify script tag and inline the library
const DEVTAG =
	/<!-- Build step.*?-->\s*<script src="node_modules\/dompurify.*?"><\/script>/s;
const inlined = html.replace(DEVTAG, `<script>${purify}</script>`);

mkdirSync(resolve(root, "dist"), { recursive: true });
writeFileSync(resolve(root, "dist/teleprompter.html"), inlined, "utf8");

const bytes = Buffer.byteLength(inlined, "utf8");
console.log(`Built: dist/teleprompter.html (${bytes} bytes)`);

// Generate worker/src/template.ts so the Worker can import the HTML and demo
// script as TypeScript modules (avoids HTML/MD module resolution issues in
// Miniflare/vitest).
const demoScript = readFileSync(
	resolve(root, "scripts/jfk-inaugural.md"),
	"utf8",
);
const templateTs =
	`// THIS FILE IS GENERATED BY scripts/build.js — DO NOT EDIT MANUALLY.\n` +
	`// Run \`npm run build\` to regenerate from teleprompter.html.\n` +
	`export const HTML = ${JSON.stringify(inlined)};\n` +
	`export const DEMO_SCRIPT = ${JSON.stringify(demoScript)};\n`;
writeFileSync(resolve(root, "worker/src/template.ts"), templateTs, "utf8");
console.log("Generated: worker/src/template.ts");
